# Generated by Django 5.0.6 on 2024-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitunguu_app', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
